apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  ports:
    - port: 5601
      targetPort: 5601
  selector:
    app: kibana
  type: NodePort  # or LoadBalancer if you don't have a LoadBalancer set up