replicaCount: 1

image:
  repository: docker.elastic.co/kibana/kibana
  tag: 7.10.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5601

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  elasticsearch_hosts: http://elasticsearch:9200
