replicaCount: 1

image:
  repository: fluent/fluentd
  tag: v1.12-debian
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 24224

config:
  # Add your custom Fluentd configuration here
  fluentd.conf: |
    <source>
      @type forward
      port 24224
    </source>
    <match **>
      @type elasticsearch
      host elasticsearch.default.svc.cluster.local
      port 9200
    </match>
