replicaCount: 1

image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 7.10.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9200

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

env:
  discovery_type: single-node
